### ISSUE TITLE
Failed to load ibdesignable from path (null) via cocoapods

### ISSUE THREAD

**Issue by Kengi** [Eddpt/EAColourfulProgressView#1]
via cocoapods  install  EAColourfulProgressView
xcode tip error: Failed to load ibdesignable from path (null)
I missed something？
Please check or make one 'storyboard' demo via cocoapods  to make sure it's work

THX

**Comment by Eddpt** [comment]
Unfortunately I haven't found a fix for this. This is a currently known issue with all cocoapods libraries that make use of live rendering. If you download this repo and run the sample it works, but it is not currently working when adding EAColourfulProgressView as a pod dependency.

See the issue [here](http://stackoverflow.com/questions/26567650/live-rendering-a-custom-component-using-ib-designable-from-a-pod-dependency)

**Comment by pbamma** [comment]
(Had to import direct as the control wasn't rendering, but that went as expected).   
- Looks like the View has a minimum (visual) limit on height if showLabels=YES.  A "nice to have" might consider putting these start/end labels embedded into the bar if statusViewHeight < 40... or whatever.  :)  Thanks for the easy to use control.

**Comment by Eddpt** [comment]
This has been fixed with the latest beta version of Cocoapods, take a look at my answer [here](http://stackoverflow.com/a/28108248/764822).

I'm closing this issue, you can open a new one as enhancement for your "nice to have" suggestion. 
Thanks.
