### ISSUE TITLE
IBDesignables

### ISSUE THREAD

**Issue by pbamma** [Eddpt/EAColourfulProgressView#2]
In XCode 6.3, I've recently found that IBDesignables have been giving me guff (I can't do anything with the xcode project that won't incur a death beach ball... even closing the project).

I've had to remove this small EAColourfulProgressView pod to gain control of my project again.  I believe this to be an XCode issue and not the problem of your fine progress view, but I figured I'd give you a heads up.

**Comment by Eddpt** [comment]
Hi, Thanks for the input. Yes I've read about the issue, i think the following stackoverflow questions are related to it:
- [Xcode 6.3 freezes/hangs after opening XIB file](http://stackoverflow.com/questions/29544738/xcode-6-3-freezes-hangs-after-opening-xib-file)
- [Xcode 6.3 Crashes when navigating from storyboard to other Swift 1.2 file](http://stackoverflow.com/questions/29542356/xcode-6-3-crashes-when-navigating-from-storyboard-to-other-swift-1-2-file)

It seems that the issue happens mostly when using custom fonts as well.

For the time being you can:
1) Go back to using Xcode 6.2, easily downloadable through the [Developer's Portal](http://adcdownload.apple.com/Developer_Tools/Xcode_6.2/Xcode_6.2.dmg)
2) Try Xcode 6.4 beta, there've been some reports on stackoverflow that the new beta version might have fixed some of the issues.
3) Temporarily point your pod to this branch: `disabled-ibdesignable`:
`pod 'EAColourfulProgressView', :git => 'https://github.com/Eddpt/EAColourfulProgressView.git', :branch => 'disabled-ibdesignable'`

I'll leave the branch there and this issue open until Apple properly fixes the issue.

**Comment by Eddpt** [comment]
This issue seems to be fixed in the latest Xcode version, 6.3.1. Closing.
